# ROUTING PARA HOME PUBLICATION
home_publication:
    path: /home
    defaults: { _controller: AppBundle:Publication:index }
# ROUTING PARA CONSULTA AJAX (ELIMINA MIS PUBLICACIONES)
remove_publication:
    path: /publication/remove/{id}
    defaults: { _controller: AppBundle:Publication:removePublication, id:null }
